//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 09:39:10 PM IST 
//


package rzd.pktbcdt.aszp.soap.ws.model;

import rzd.pktbcdt.aszp.soap.ws.WSEndpoint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 *
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = WSEndpoint.GET_PROJECT_RESPONSE_LOCAL_PART,
        propOrder = {
        "projects"
        },
        namespace = WSEndpoint.NAMESPACE_URI
)
@XmlRootElement(name = WSEndpoint.GET_PROJECT_RESPONSE_LOCAL_PART, namespace = WSEndpoint.NAMESPACE_URI)
public class GetProjectsResponse {

    @XmlElement(name = "Projects", required = true, namespace = WSEndpoint.NAMESPACE_URI)
    //    @XmlSchemaType(name = "Projects", namespace = WSEndpoint.NAMESPACE_URI)
    private List<Project> projects;

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link Project }
     *     
     */
    public List<Project> getProjects() {
        return projects;
    }



    /**
     * Sets the value of the project property.
     *
     * @param projects
     *     allowed object is
     *     {@link Project }
     *
     */
    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

}
