//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 09:39:10 PM IST 
//


package rzd.pktbcdt.aszp.soap.ws.model;

import rzd.pktbcdt.aszp.soap.ws.WSEndpoint;

import javax.xml.bind.annotation.*;
import java.util.Date;
import java.util.List;


/**

 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = WSEndpoint.GET_ASZP_PROJECT_REQUEST_LOCAL_PART, propOrder = {
    "idProjectList"
        ,"date"
    },
        namespace = WSEndpoint.NAMESPACE_URI
)
@XmlRootElement(name = WSEndpoint.GET_ASZP_PROJECT_REQUEST_LOCAL_PART, namespace = WSEndpoint.NAMESPACE_URI)
public class ProjectsRequest {

    @XmlElement(
            required = false, nillable = true
            , namespace = WSEndpoint.NAMESPACE_URI
    )
    private List<Long> idProjectList;
    @XmlElement(name = "dateEndProject", required = false, nillable = true, namespace = WSEndpoint.NAMESPACE_URI)
    @XmlSchemaType(name = "dateTime")
    private Date date;

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public List<Long> getIdProjectList() {
        return idProjectList;
    }

    public void setIdProjectList(List<Long> idProjectList) {
        this.idProjectList = idProjectList;
    }

    @Override
    public String toString() {
        return "ProjectsRequest{" +
                "idProjectList=" + idProjectList +
                ", date=" + date +
                '}';
    }
}
