//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 09:39:10 PM IST 
//


package rzd.pktbcdt.aszp.soap.ws.model;

import rzd.pktbcdt.aszp.soap.ws.WSEndpoint;

import javax.xml.bind.annotation.*;
import java.util.Date;


/**

 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = WSEndpoint.GET_PROJECT_INFO_REQUEST_LOCAL_PART, propOrder = {
    "idProject"
    ,"year"
    },
        namespace = WSEndpoint.NAMESPACE_URI
)
@XmlRootElement(name = WSEndpoint.GET_PROJECT_INFO_REQUEST_LOCAL_PART, namespace = WSEndpoint.NAMESPACE_URI)
public class ProjectsInfoRequest {



    @XmlElement(name = "year", required = true, nillable = false, namespace = WSEndpoint.NAMESPACE_URI)
    private Integer year;
    @XmlElement(name = "idProject", required = true, nillable = false, namespace = WSEndpoint.NAMESPACE_URI)
    private Long idProject;



    public Long getIdProject() {
        return idProject;
    }

    public void setIdProject(Long idProject) {
        this.idProject = idProject;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public Integer getYear() {
        return year;
    }

    /**
     * Sets the value of the Year property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setYear(Integer value) {
        this.year = value;
    }

    @Override
    public String toString() {
        return "GetProjectsRequest{" +
                "year=" + year +
                ", idProject='" + idProject + '\'' +
                '}';
    }
}
